### ISSUE TITLE
related article

### ISSUE THREAD

**Issue by che-wenchao** [apolat2018/Landslide-Susceptibility-Assessment-Tool#1]
Are there any academic articles related to this project?

**Comment by apolat2018** [comment]
I have submitted manuscript. It's in under review. I will share when it is published.
Thanks.

**Comment by apolat2018** [comment]
This repository has been moved to https://github.com/apolat2018/LSAT. Please follow this link.

**Comment by apolat2018** [comment]
This repository has been moved to https://github.com/apolat2018/LSAT.
